version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRE_USER=postgre
      - POSTGRE_PASSWORD=postgre
      - POSTGRE_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgre_catalog:/var/lib/postgresql/data